"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from login_and_registration.models import Config

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = Config.objects.get(key='SECRET_KEY').value
# 'd2evgapr8o%ijtim5j9fktgxp_!m_*o1#ml!ig#)6uv(i9fnhu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'login_and_registration',
    'browse',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
#  FILE STORAGE
DEFAULT_FILE_STORAGE = Config.objects.get(key='DEFAULT_FILE_STORAGE').value
#
# STATIC STORAGE
STATICFILES_STORAGE = Config.objects.get(key='STATICFILES_STORAGE').value
#
# AWS ACCCESS key
<<<<<<< HEAD
AWS_ACCESS_KEY_ID = Config.objects.get(key='AWS_ACCESS_KEY_ID').value
#
# AWS SECRET KEY
AWS_SECRET_ACCESS_KEY = Config.objects.get(key='AWS_SECRET_ACCESS_KEY').value
=======
AWS_ACCESS_KEY_ID = 
#
# AWS SECRET KEY
AWS_SECRET_ACCESS_KEY = 
>>>>>>> 3f88b812b0e335984ae82fdb7c4f2114384ed449
#
# AWS STORAGE BUCKET NAME
AWS_STORAGE_BUCKET_NAME = Config.objects.get(key='AWS_STORAGE_BUCKET_NAME').value
#
# AWS DEFAULT ACL
AWS_DEFAULT_ACL = Config.objects.get(key='AWS_DEFAULT_ACL').value
#
# create bucket auto
AWS_AUTO_CREATE_BUCKET = Config.objects.get(key='AWS_AUTO_CREATE_BUCKET').value
#

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
